### ISSUE TITLE
Can we use this with ALL now deployments?

### ISSUE THREAD

**Issue by SteveALee** [zeit/micro-proxy#20]
The README says

> But if you are using ZEIT now, you can simply use path alias rules instead.
(It's a FREE service available for all ZEIT now deployments.)

but the now docs say  

> If you manage your domain inside ZEIT or point it to alias.zeit.co, you can hide microservices under a domain as shown above with our "Path Alias" feature.

It appears neither domain option is available with the OSS pricing. 
Or perhaps I got the CNAME pointing wrong?

**Comment by jamo** [comment]
*.now.sh domains can freely be used with all plans.
Similarly to custom domains, *.now.sh domains can be used with path aliases.

**Comment by SteveALee** [comment]
Ah yes, I wad thinking of custom domains. Thanks
