### ISSUE TITLE
use the path of the destination in the request

### ISSUE THREAD

**Issue by jwilson64** [zeit/micro-proxy#28]
Hello,

I am currently working on a multi-tenant app and for testing I am trying to use micro-proxy.

What I have set up right now is to micro-scripts to proxy. one running on port 9000 and one on 9001

the rules in question would be similar to this: 

hit 9000 and get this
```
{
  "rules": [
    {"pathname": "/**", "dest": "http://localhost:3000/tenantA"}
  ]
}
``` 

hit 9001 and get this
```
{
  "rules": [
    {"pathname": "/**", "dest": "http://localhost:3000/tenantB"}
  ]
}
``` 

I would expect going to localhost:9000 would return me the view from localhost:3000/tenantA but it instead gives me the root path for localhost:3000.

Is there something that I can do to ensure that I would end up hitting localhost:3000/tenantA/index or something along those lines?

**Comment by jwilson64** [comment]
I forked the proxy and it looks like the fix pathname is causing some of the issues. With linter moving it looks like it won't go to the fallback on the regex to `.*` I commented out lines 116 -> 122 of `lint-rules.js` and now my regex works fine. If I set it to `.*` in the pathname it picks that up and adjust it to `^.*$` appropriately.

I then had to replace/remove the beginning `/` from the url per the url.resolve documentation in node.js in the proxyRequest function of index.js.

**Comment by jwilson64** [comment]
Should be fixed by my PR adding appending mode. See: #33

**Comment by sushruth** [comment]
Supporting `pathRewrite` as in !21 can help with this. You can probably use JS compatible regexp with that kind of rewrite to achieve this.

**Comment by tsnolan23** [comment]
@sushruth can you provide an example of how your `pathRewrite` branch could achieve this? We have a similar issue

**Comment by jwilson64** [comment]
So if you look up https://github.com/zeit/micro-proxy/pull/33 this is how I resolved this. I am working on a fork right now to support more features and wanted to push back upstream with my changes. They don't want to support a whole lot on this from the looks of things.

**Comment by sushruth** [comment]
@tsnolan23 You could possibly use it like this.

```
{
  "rules": [
    {
      "pathname": "/foo/bar",
      "dest": "http://localhost:3000/",
      "rewrites": {
        "(.*)": "nested/$1"
      }
    }
  ]
}
```
