### ISSUE TITLE
pathname RegExp wrong with certain characters

### ISSUE THREAD

**Issue by Boogie97** [zeit/micro-proxy#29]
If you have a simple rule file like this:

```
{
  "rules": [
    {"pathname": "/foo-bar/**", "dest": "http://localhost:3000"},
    {"dest": "http://localhost:4000"}
  ]
}
```
The rule for `/foo-bar/**` won't work, because the RegExp will be generated to `^/foo/\\-/bar/(.*)$`, but it should be `^/foo\-bar/(.*)$`.  

I think this is because of this line: 
https://github.com/zeit/micro-proxy/blob/f20f5f46a39bce3a42fd1b0c7bbcd1deff818bde/lib/lint-rules.js#L117

The RegExp in this line is replaced by another RegExp `/\\$&/`. If I change it to a string `'\\$&'` it works fine for me.

The same goes wrong for the dot character `.`.

**Comment by jwilson64** [comment]
I found that the check for pathname didn't always hit on it. I added a change that works for me in a lot more cases when I use it locally. See if the lint change at the bottom fixes it for you: #33 

```
124     rule.pathnameRe = `^(${pathnameRe})$`
```

**Comment by Boogie97** [comment]
Thank you for your response. I think your solution with the appending mode is a really good idea. But i doubt this solves my problem with `-` in pathname rules if the pathname also includes `*`. Either way, for local testing I can change the code of micro-proxy, but this issue also exists in production on ZEIT now (with alias rules), which is my real problem.

**Comment by jwilson64** [comment]
Yeah, I ran into this as well and found the pathname regex broke without wrapping pathnameRe in `( )` like this:
```   
rule.pathnameRe = `^(${pathnameRe})$`
```
