### ISSUE TITLE
Invalid Host Header

### ISSUE THREAD

**Issue by babenzele** [zeit/micro-proxy#9]
When using ngrok or a similar service and visiting the url in the browser, I am seeing "Invalid Host Header" printed in the browser. When using [now-server](https://github.com/markmarijnissen/now-server) I do not see this error.

I'm guessing it's because the ngrok domain does not match the localhost domain.

**Comment by babenzele** [comment]
Seems like this error is coming from webpack. I set `devServer.https` to true and connected to `https://localhost` and it worked. Now I have to figure out how not to connect over https...

**Comment by babenzele** [comment]
Setting [`devServer.allowedHosts`](https://webpack.js.org/configuration/dev-server/#devserver-allowedhosts) fixed this for me.

**Comment by Zertz** [comment]
@tim-phillips I don't quite understand how you managed to fix this, would you mind sharing a few more details? i'm using Forward (similar to ngrok) and running into the same issue.

**Comment by tim-phillips** [comment]
@Zertz In `webpack.config.js` I set `allowedHosts: ['.ngrok.io']`.

Here's my full webpack config. For this project I'm serving a `.js` bundle without any html.

```javascript
require('dotenv').config()
const path = require('path')
const Dotenv = require('dotenv-webpack')

const dev = process.env.NODE_ENV !== 'production'

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
    chunkFilename: '[name].bundle.js',
    publicPath: 'https://' + process.env.APP_DOMAIN + '/scripts/'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: 'babel-loader',
        exclude: /node_modules/
      }
    ]
  },
  devtool: dev ? 'eval-source-map' : false,
  devServer: {
    contentBase: path.resolve(__dirname, 'dist'),
    allowedHosts: ['.ngrok.io'],
    port: 4005,
    compress: true,
    inline: false
  },
  plugins: [new Dotenv()]
}
```
